// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQpaE6AzhAHIrM0g5oNptTisKAjnGtlQI',
    appId: '1:352030331822:web:099b722105808b615d6e3f',
    messagingSenderId: '352030331822',
    projectId: 'job-finder-app-7d191',
    authDomain: 'job-finder-app-7d191.firebaseapp.com',
    storageBucket: 'job-finder-app-7d191.firebasestorage.app',
    measurementId: 'G-6YNRMZ9RX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS1Tr4jyhCiIe0KmMgyZGTg40o43FqMZM',
    appId: '1:352030331822:android:a226fce64047e30a5d6e3f',
    messagingSenderId: '352030331822',
    projectId: 'job-finder-app-7d191',
    storageBucket: 'job-finder-app-7d191.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNBitoOym1uP69KqKU-vZxGFZQFLpc2k',
    appId: '1:352030331822:ios:f27039d9608f14f55d6e3f',
    messagingSenderId: '352030331822',
    projectId: 'job-finder-app-7d191',
    storageBucket: 'job-finder-app-7d191.firebasestorage.app',
    iosBundleId: 'com.iqraconnect.app',
  );
}
